# -*- mode: ruby -*-
# vi: set ft=ruby :
#
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.define :control, primary: true do |control|
    control.vm.network "private_network", ip: "192.168.33.10"
    control.vm.hostname = "control.example.com"
    control.vm.synced_folder "data/control", "/vagrant"
  end

  config.vm.define :target do |target|
    target.vm.network "private_network", ip: "192.168.33.11"
    target.vm.hostname = "target.example.com"
    target.vm.synced_folder "data/target", "/vagrant"
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook="setup.yml"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

#  config.vm.provider "virtualbox" do |lv|
#    lv.memory = "1024"
#  end

  config.ssh.insert_key = false
end
